
    b1=document.querySelector('.b1');
    b1.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="1";
    });
    b2=document.querySelector('.b2');
    b2.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="2";
    });
    b3=document.querySelector('.b3');
    b3.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="3";
    });
    b4=document.querySelector('.b4');
    b4.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="4";
    });
    b5=document.querySelector('.b5');
    b5.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="5";
    });
    b6=document.querySelector('.b6');
    b6.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="6";
    });
    b7=document.querySelector('.b7');
    b7.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="7";
    });
    b8=document.querySelector('.b8');
    b8.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="8";
    });
    b9=document.querySelector('.b9');
    b9.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="9";
    });
    bplu=document.querySelector('.bplu');
    bplu.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="+";
    });
    bmin=document.querySelector('.bmin');
    bmin.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="-";
    });
    bmul=document.querySelector('.bmul');
    bmul.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="*";
    });
    bdiv=document.querySelector('.bdiv');
    bdiv.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="/";
    });
    b0=document.querySelector('.b0');
    b0.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        scr.innerText+="0";
    });
    beq=document.querySelector('.beq');
    beq.addEventListener("click",()=>{
        scr=document.querySelector('.screen');
        let a=scr.innerText;
        
        scr.innerText+="=";
        scr.innerText=eval(a);
     });
     bac=document.querySelector('.bac');
     bac.addEventListener("click",()=>{
         scr=document.querySelector('.screen');
         scr.innerText="";
     });

